### ISSUE TITLE
Bug in beta diversity app with duplicate key value

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/service-eda-compute#46]
Encountered on Anopheles albimanus data. Opened a beta diversity app, chose "Order" as the data and either "bray" or "jaccard" as the method and hit this error message when trying to generate results. Did not get the error message (app worked as expected) when the data was "Class"
<img width="669" alt="Screenshot 2023-02-28 at 1 55 53 PM" src="https://user-images.githubusercontent.com/54597319/221952615-d4361ee7-2198-435a-b0b2-d6f718f7ac7a.png">

**Comment by dmfalke** [comment]
This looks like a compute service error. Tagging @dmgaldi, in case it's related to some other issues you were looking at.

**Comment by ryanrdoherty** [comment]
This looks like a duplicate of https://github.com/VEuPathDB/lib-compute-platform/issues/29.  Ellie just released a new version of lib-compute with the fix, so we should just need to upgrade on eda-compute and release.

**Comment by ryanrdoherty** [comment]
I see she just did so.  I updated qa/feat tagger so this should be up in a few minutes.

**Comment by dmgaldi** [comment]
Thanks Ryan, the issue I fixed was just causing the actual error to be masked by a metrics failure.

**Comment by dmfalke** [comment]
Can I close this?

**Comment by asizemore** [comment]
Just checked on the live site. All is working! Closing.
