### ISSUE TITLE
Add constraints for compute plugins

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/service-eda-compute#57]
Some plugins only work for particular types of data. We'd like to create a way for the plugin to say "i only take x, y, and z data, not a, b, or c data". 

This work depends on https://redmine.apidb.org/issues/51838. 

See discussion in https://github.com/VEuPathDB/EdaDataService/issues/227 for more details and prior thinking.

**Comment by dmgaldi** [comment]
@d-callan This should be available in dev now
