### ISSUE TITLE
Explore alternative correlation endpoint structures

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/service-eda-compute#71]
Suggested in https://github.com/VEuPathDB/service-eda-compute/pull/61#discussion_r1370555285

Instead of making the following endpoints:
- /correlationassaymetadata
- /correlationassayassay (or similar)
- /correlationmetadatametadata (or similar)

could we instead do
- /correlation/assaymetadata
- /correlation/assayassay
- /correlation/metadatametadata

?

**Comment by asizemore** [comment]
@d-callan now that we have a second app up and going, does that change your opinion on the above?

**Comment by d-callan** [comment]
I still think this would be great to do, but understand it may not be worth the effort
